"""user avatar_hash

Revision ID: 2cbf429ae747
Revises: c3ee730ddc8b
Create Date: 2017-07-06 20:27:10.849381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cbf429ae747'
down_revision = 'c3ee730ddc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###
