"""user realname

Revision ID: c3ee730ddc8b
Revises: e85d18e83d20
Create Date: 2017-07-05 21:33:31.575776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3ee730ddc8b'
down_revision = 'e85d18e83d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('realname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'realname')
    # ### end Alembic commands ###
